### ISSUE TITLE
Incorrect text colours for results if previous search was cancelled/deleted

### ISSUE THREAD

**Issue by HippoPenguin** [serphacker/serposcope#107]
For example.

I check the ranks for today. I then cancel it whilst its 10% of the way through for whatever reason.
I then delete that scan from the Task list.
I run the check again.
Once it's all done everything shows up as green (up rank) because it seems to remember the previous scan but as that scan no longer exists/didn't finish it counts it as 0.

**Comment by serphacker** [comment]
Yes I ACK the bug but I won't fix. Too much works for little gain: deleting run is not something common, also we are going to provide a new way to recheck failed position which should make "run deletion" even rarer.
