### ISSUE TITLE
Priority Keywords + Calendar Events Request

### ISSUE THREAD

**Issue by samunderwood** [serphacker/serposcope#111]
Two requests, one is to be able to select keywords as a priority and sort or filter to show priority keywords.

Also it possible to have calendar events show up on charts?

**Comment by serphacker** [comment]
I thought I did add calendar events on the charts too but it looks like they are missing

priority keyword or something like that is likely to be implemented but not soon

**Comment by serphacker** [comment]
Calendar event is already shown on chart. We won't implement priority keyword now (we did not decide if we use search volume or priority).
