### ISSUE TITLE
would run the application in cloud9 IDE environment

### ISSUE THREAD

**Issue by selique** [serphacker/serposcope#113]
would run the application in cloud9 IDE environment, it is a unbuntu machine.

I configured and installed as it may make it a unbuntu User machine, but do not know how to run the application

https://ide.c9.io/selique/serposcope following environmental link (send me an email for me to authorize access I share)

**Comment by serphacker** [comment]
Hi, sorry i did try to connect to your online IDE but I didn't manage to understand how to use it sorry. you need to run mvn ninja:run, check the dev instruction on serpocope github.
