### ISSUE TITLE
too big usage

### ISSUE THREAD

**Issue by Cykucjusz** [serphacker/serposcope#117]
![intel core i7 stopped](https://cloud.githubusercontent.com/assets/18418608/15798450/af305f68-2a41-11e6-8f61-11aacf3e524d.jpg)
![intel core i7](https://cloud.githubusercontent.com/assets/18418608/15798449/af2f82fa-2a41-11e6-8939-0ded9e4c7b39.jpg)

Windows 10 x64

**Comment by serphacker** [comment]
Need more information.

**Comment by Cykucjusz** [comment]
This is usage in started/stoped service in NON SERP SCAN mode

**Comment by serphacker** [comment]
how many keywords in the database ? anyway it shouldn't do that. Do you have an antivirus or something ? If yes, shut it down and tell me how things are going

**Comment by Cykucjusz** [comment]
When MCAFEE is disabled usage is normal

**Comment by serphacker** [comment]
I'm afraid there is little I can do about that. Only McAfee can resolve this issue I think. Maybe you can whitelist serposcope processes ? Or maybe it's just a random scan and it will stop after a while.
