### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by lyonzy** [serphacker/serposcope#119]
Hello,

First of all good work - Serposcope is going well for me so far :)

I was wondering if we could have a facility to specify a robots.txt for the Serposcope dashboard? I don't really want/need my personal instance being indexed.

Cheers,
Matt

**Comment by serphacker** [comment]
serposcope is noindex check the HTTP headers.
```
curl -v http://localhost:7777/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7777 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:7777
> Accept: */*
> 
< HTTP/1.1 303 See Other
< Date: Fri, 01 Jul 2016 13:05:59 GMT
< X-Frame-Options: deny
< X-Robots-Tag: noindex, nofollow
```

**Comment by lyonzy** [comment]
Ah, right, so it is. Cheers :)
