### ISSUE TITLE
Shared checking/scraping

### ISSUE THREAD

**Issue by serphacker** [serphacker/serposcope#13]
Allow peoples to scrap together Google SERP and share their results. So if user A already scraped SERP for keyword X, user B can use the scrap of A without making request to Google.

2 problems: 
_ privacy, some people don't want to share their scrap (keywords disclosure). That's why it will be opt out by default.
_ poisonning: a malicious user could upload fake SERP with invalid ranking (more details here http://blog.serphacker.com/fr/03-update-serposcope-1.0.3.html (french) ).

**Comment by lury** [comment]
another issue is related to geolocalization of results - this should be taken into account when merging data.
Timezones also.

**Comment by serphacker** [comment]
won't implement this feature
