### ISSUE TITLE
Trying to add search/website as a user and getting an error

### ISSUE THREAD

**Issue by mit686** [serphacker/serposcope#133]
unauthorized access or session expired

**Comment by EmbDclic** [comment]
Same bug when you try to add an event to the calendar when logged in as a user.
![capture](https://cloud.githubusercontent.com/assets/23118296/20030605/f37842d0-a368-11e6-8ab8-7dc96cc871f5.PNG)

**Comment by serphacker** [comment]
only admin is authorized to edit search/event on serposcope. Simple user are "read-only" users

**Comment by mit686** [comment]
Why don't give a user write permissions as well?

**Comment by EmbDclic** [comment]
If you give write permissions to a user, then it's the same as an admin. I think it's a good thing to have user => read-only, admin => read/write.

But for a user, the button "Add event to calendar" shouldn't been displayed, especially the popup where he can fill in all the event infos, but will have an error only on clicking the "Save" button.

**Comment by mit686** [comment]
Thanks for your reply, 
A regular user will not be same as admin because he has access only to specific groups only.
So, all I need is to give that user write permissions to these specific groups as well.
Does it make sense?

**Comment by EmbDclic** [comment]
My bad, I thought an admin could be assigned to groups as users are (except the first admin), but admins have automatically access to all groups.
