### ISSUE TITLE
Ubuntu Install

### ISSUE THREAD

**Issue by AwakenedOne** [serphacker/serposcope#143]
Pasted from terminal:

~$ systemctl status serposcope.service
● serposcope.service - LSB: serposcope rank checker
   Loaded: loaded (/etc/init.d/serposcope; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2016-12-15 16:48:50 MST; 38s ago
     Docs: man:systemd-sysv-generator(8)

Dec 15 16:48:50 greg-Precision-M6500 systemd[1]: Starting LSB: serposcope rank c
Dec 15 16:48:50 greg-Precision-M6500 serposcope[7037]: Can't find JAVA_HOME, jav
Dec 15 16:48:50 greg-Precision-M6500 systemd[1]: serposcope.service: Control pro
Dec 15 16:48:50 greg-Precision-M6500 systemd[1]: Failed to start LSB: serposcope
Dec 15 16:48:50 greg-Precision-M6500 systemd[1]: serposcope.service: Unit entere
Dec 15 16:48:50 greg-Precision-M6500 systemd[1]: serposcope.service: Failed with
lines 1-11/11 (END)

And that's it. It just hangs from there. 

Java is up to date and Ubuntu version 16.0.4

**Comment by serphacker** [comment]
Not related to ubuntu.

serposcope can't find you java installation. Follow install instruction, if you did set up java manually specify java_home according to install instructions (somewhere in /etc/default/serposcope)

**Comment by AwakenedOne** [comment]
I had a bad install of Ubuntu. Wiped hard drive and installed from scratch and it works perfectly!
