### ISSUE TITLE
Cannot import keywords in bulk

### ISSUE THREAD

**Issue by cpozzer** [serphacker/serposcope#145]
I have tried in all ways, with without location, with without device, mobile non mobile and i always get this error ....is and invalid device type.... there is no way to import keywords in bulk, i even tried to export a keyword i added single and used the same sequence to import in bulk, nothing. Just doesnt work

**Comment by supamerz** [comment]
Hey cpozzer,

What version of serposcope are you running? What OS? Latest Java JDK?

I just bulk imported keywords on my local Windows 8.1 OS running Java 1.8.0 111 with no issues in browser or console on 2.6.0 of serposcope.

**Comment by cpozzer** [comment]
Thanks for getting back to me, after 2 hours of trying i figured out the issue, basically what i did was to import a single keyword and then export it, with that layout i imported 20 keywords at a time, and it worked. Now dont ask me why importing in bulk 250 keywords i was getting that error.
Ver 2.6 Windows 2008R2 Chrome

**Comment by serphacker** [comment]
please paste a sample of the data you can't import
