### ISSUE TITLE
error maven can't find dependencies

### ISSUE THREAD

**Issue by othmanoss** [serphacker/serposcope#164]
hi 
im trying to buid project first time i get this error

"The POM for com.serphacker.serposcope:scraper:jar:2.7.1 is missing, no dependency information available"
`[ERROR] Failed to execute goal on project web: Could not resolve dependencies for project com.serphacker.serposcope:web:jar:2.7.1: Failure to find com.serphacker.serposcope:core:jar:2.7.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

thanks in advance

**Comment by serphacker** [comment]
did you follow https://github.com/serphacker/serposcope/blob/master/BUILD-INSTRUCTIONS.md

**Comment by othmanoss** [comment]
yes

**Comment by othmanoss** [comment]
its work now after using prod cmd : 
`mvn -Dsinglejar=true -Dminify=true clean install`

thanks
