### ISSUE TITLE
how can i use it?

### ISSUE THREAD

**Issue by hamed1618** [serphacker/serposcope#170]
is it andorid app? should i open it with android studio?

**Comment by lutek** [comment]
https://serposcope.serphacker.com/en/doc/faq.html

**Comment by hamed1618** [comment]
is it php or what? can i edit it to android app?

**Comment by serphacker** [comment]
it is not an android app. 

It is a java applilcation (server side backend) with some html/javascript (frontend).

You access the app via a browser (so a mobile browser/android is ok).

**Comment by hamed1618** [comment]
i should open the project with netbeans? can i open it with android studio?

**Comment by serphacker** [comment]
better to use netbeans/eclipse or idea intellij than android studio

**Comment by hamed1618** [comment]
thank you
