### ISSUE TITLE
anti-captcha.com broken

### ISSUE THREAD

**Issue by rapidmod** [serphacker/serposcope#181]
www.anti-captcha.com

The site only works with OUT the www part. Captcha solving is broken with this service. When testing the credentials from admin I get an alert with a "failed to log in service anticaptcha (invalid credentials)" message

**Comment by noguespi** [comment]
no, it uses api.anti-captcha.com and it works.

**Comment by rapidmod** [comment]
I tried resetting the API key and testing all I get is an alert that pops up saying "failed to log in service anticaptcha (invalid credentials)" They are not invalid I double and triple checked. The account still has money in it
![api settings](https://user-images.githubusercontent.com/7457517/34613485-fb61dab4-f1fb-11e7-9d3e-6bbc5d14e497.jpg)


The link in the settings page redirects to www and does NOT work
![settings](https://user-images.githubusercontent.com/7457517/34613344-6dac166c-f1fb-11e7-9b60-8ae9087c9daf.jpg)
