### ISSUE TITLE
anti-captcha.com is NOT working

### ISSUE THREAD

**Issue by rapidmod** [serphacker/serposcope#182]
Under Admin > Settings 

Please let me know where I can get additional information to help you, but this is what I have.

The test button for the api in admin displays a modal with an error that says: "failed to log in service anticaptcha (invalid credentials)"

The account is valid see screenshot: I can also use the API with PHP and my credentials and it works fine.

![api settings](https://user-images.githubusercontent.com/7457517/34638565-24d72bec-f29c-11e7-9d9a-61cb66c649ff.jpg)

Also, the URL that redirects to "www.anti-captcha.com" doesn't work properly. The site no longer loads with www

![settings](https://user-images.githubusercontent.com/7457517/34638581-8d7c7fa8-f29c-11e7-8254-14875e056488.jpg)

I haven't been able to successfully check ranks since the service has broken. The pause is set at 60 seconds. I manually started this search 20 min ago and already 3 captchas and 108 errors

![tasks](https://user-images.githubusercontent.com/7457517/34638614-1c8ef126-f29d-11e7-88a6-d0e89a0af541.jpg)

**Comment by noguespi** [comment]
It works. anti-captcha server was probably overloaded, it happens all the time, that's why I'm adding more captcha solving service in 2.9.
