### ISSUE TITLE
Use Serposcope to improve our Serp API Tool?

### ISSUE THREAD

**Issue by hartator** [serphacker/serposcope#188]
Hello,

Congrats on your awesome tool, we're wondering if we can use some of your work inside our tool?

Disclaimer: We've just released a [Serp API Tool](https://github.com/serpapi/google-search-results-java/graphs/traffic), and also a [Java library](https://github.com/serpapi/google-search-results-java). We think we can use part of your code to improve a bit both. We know you've released your code under a MIT License, but we rather ask you directly. It's perfectly fine if you rather not.

**Comment by noguespi** [comment]
yes you can
