### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by mlake** [serphacker/serposcope#189]
Bonjour Pierre..

Love your tool - would love to get mobile SERPs working though. I saw in the unreleased 2.9.0 changelog that you have some fixes already so tried building from source, but i'm getting the following errors. Perhaps you haven't committed all your code??

Thanks,
Michael
(FYI, I'm also in Paris - so if you're interested in getting drinks some time, I'd be happy to buy you a beer in person)

![image](https://user-images.githubusercontent.com/764071/38722531-7bc656d6-3efe-11e8-9497-27748b999485.png)

**Comment by noguespi** [comment]
check https://github.com/serphacker/serposcope/blob/master/BUILD-INSTRUCTIONS.md this error is due to querydsl code generation which should be done before compiling.

**Comment by noguespi** [comment]
(and 2.9.0 has been released with mobile search fix)
