### ISSUE TITLE
Improve Debian package

### ISSUE THREAD

**Issue by dugwood** [serphacker/serposcope#193]
I've looked at this repository code, but couldn't find the script that create the Debian package.

So my request is to change the file `/etc/init.d/serposcope` to find Java 8 in amd64 environment. As you can see:
```
ls /usr/lib/jvm/
default-java  java-1.5.0-gcj-6-amd64  java-1.8.0-openjdk-amd64  java-8-openjdk-amd64
```
The directory is `java-8-openjdk-amd64`.

I've installed `openjdk-8-jdk` and `openjdk-8-jre`

Of course I can create a link, but the idea is to make things easy for everyone (i'm sure you agree!).

So:
```
JVM_SEARCH_DIRS="/usr/lib/jvm/java-8-oracle /usr/lib/jvm/java-8-openjdk /usr/lib/jvm/java-8-sun /usr/lib/jvm/java-9-oracle /usr/lib/jvm/java-9-openjdk /usr/lib/jvm/java-9-sun"
```
become:
```
JVM_SEARCH_DIRS="/usr/lib/jvm/java-8-oracle /usr/lib/jvm/java-8-openjdk /usr/lib/jvm/java-8-openjdk-amd64 /usr/lib/jvm/java-8-sun /usr/lib/jvm/java-9-oracle /usr/lib/jvm/java-9-openjdk /usr/lib/jvm/java-9-sun"
```

Thanks!

**Comment by noguespi** [comment]
define JAVA_HOME variable in /etc/default/serposcope

**Comment by dugwood** [comment]
Thanks for the info, but wouldn't it be useful for every Debian AMD64 user to just install and run the service? As it's a Debian/Ubuntu specific script, I thought it would be helpful.

**Comment by noguespi** [comment]
yes you are right, the packaging should be reworked, but I plan to only do a single package like appimage/flatpak/snap or something else (not sure they support service/daemon application like serposcope). This way all linux distribution will be supported with a single package.

**Comment by dugwood** [comment]
OK, that makes sense :-)

Or perhaps testing all directories in `/var/lib/jvm/` for the `bin/java`? I'll close this for now.
