### ISSUE TITLE
For some keywords SERP (Blob) is getting saved as 8 bytes (NULL) and hence rankings are not displayed - MySQL

### ISSUE THREAD

**Issue by ron51** [serphacker/serposcope#200]

**Comment by timbo-lino** [comment]
Same problem here since a couple of days. Right now serposcope is unusable with this

**Comment by timbo-lino** [comment]
I have the feeling that the this software is not under active development right now.

**Comment by timbo-lino** [comment]
@ron51 pls check it out. On my side all keywords with device = mobile are having this issue. "desktop" keywords work normally

**Comment by ron51** [comment]
@timbo-lino for me even desktop keywords are not working normally, like every 1 in 10 keywords giving this problem.

**Comment by timbo-lino** [comment]
Okay....A friend had this problem with mobile keywords as well. Here I had another problem with captchas. Serposcope said that everything went fine but in the some kw were not tracked. Now I increased the pause between searches to 120|240 sec and had two perfect runs

**Comment by noguespi** [comment]
I will fix this issue soon (next week in worst case).
I'm extracting and refactoring the HTTP client into https://github.com/serphacker/webaxe. Then I will upgrade serposcope to java 11. And after I will refactor and fix the Google scraper (it will fix this issue).

**Comment by ron51** [comment]
thanks @noguespi

**Comment by noguespi** [comment]
fixed in 2.10.0
