### ISSUE TITLE
Checking the position is a horror

### ISSUE THREAD

**Issue by Cykucjusz** [serphacker/serposcope#202]
I check the positions with the help of the Anticaptcha system. For some time checking the time is not continuous, you have to check again. Checks have been checked for 2 days so that they are not. I will add that I do not use proxy when checking it is about 150 phrases. I wonder how the program behaves with more phrases. What most puzzles me in the serposcope is the fact that the positions are and the serposcope does not catch them. It is interesting that the [hostinguj.pl](https://hostinguj.pl/) has been uninterruptedly for several months under the phrase "HOSTING standard". The serposcope does not see it at all. It seems to me that Google is not sleeping.

**Comment by noguespi** [comment]
will be fixed soon see #200
