### ISSUE TITLE
Task showed success but some keywords failed

### ISSUE THREAD

**Issue by jinjie** [serphacker/serposcope#211]
Recently, I noticed that some keyword phrases have actually failed and showed the keyword ranking as **OUT**. Which in fact, the keyword is still within the top 100 ranking.

Further investigation found that there is no ranking report in that keyword. In this URI: https://example.com/google/1/search/175.

Looked in the log, found that this keyword have actually failed, but the task showed as success. What am I missing out here?

**Comment by noguespi** [comment]
Can you copy the logs to https://gist.github.com and link here ?

**Comment by ron51** [comment]
I think this issue is related to what I have logged in here 
https://github.com/serphacker/serposcope/issues/212

@jinjie @noguespi

**Comment by jinjie** [comment]
Checked the database. It shows "0" in the serp blob of GOOGLE_SERP.

Checked the log. It seem that it failed to connect to the proxy. Shouldn't it just show that errors instead of passing the tasks? It shows 0 errors in my task list for this specific day. I have extracted the log concerning to the affected keyword:

```
[2019-10-22 01:19:40,962] [google-1] INFO  c.s.s.t.g.GoogleTaskRunnable - search "rehearsal studio" | try 1 | total search done : 11/79
[2019-10-22 01:19:40,962] [google-1] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.com/search?q=rehearsal+studio&gl=sg&uule=w+CAIQICIXZG93bnRvd24gY29yZSxzaW5nYXBvcmU=&num=100 via proxy:http://180.210.201.54:3128/ try 1
[2019-10-22 01:20:47,252] [google-1] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[-1] exception=[SocketTimeoutException : Read timed out]
[2019-10-22 01:20:47,252] [google-1] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.com/search?q=rehearsal+studio&gl=sg&uule=w+CAIQICIXZG93bnRvd24gY29yZSxzaW5nYXBvcmU=&num=100 via proxy:http://180.210.201.54:3128/ try 2
[2019-10-22 01:21:10,116] [google-1] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[200] exception=[none]
[2019-10-22 01:21:10,121] [google-1] TRACE c.s.s.s.g.s.GoogleScraper - sleeping 10530 milliseconds
[2019-10-22 01:21:20,676] [google-1] INFO  c.s.s.t.g.GoogleTaskRunnable - search "rehearsal studio" | try 1 | total search done : 13/79
[2019-10-22 01:21:20,676] [google-1] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.com/search?q=rehearsal+studio&gl=sg&uule=w+CAIQICIXZG93bnRvd24gY29yZSxzaW5nYXBvcmU=&num=100 via proxy:http://52.187.65.56:3128/ try 1
[2019-10-22 01:21:31,811] [google-1] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[200] exception=[none]
[2019-10-22 01:21:31,834] [google-1] TRACE c.s.s.s.g.s.GoogleScraper - sleeping 7254 milliseconds
```

**Comment by noguespi** [comment]
I think the SERP changed to much and the parser is no more able to parse it. I'll fix it today.

**Comment by noguespi** [comment]
I am sure it is the new SERP with favicon which is causing trouble. It looks like that : 

![image](https://user-images.githubusercontent.com/1118107/67302869-d89d6480-f4f1-11e9-925d-851e11fe68dc.png)

That's a screenshort of the SERP I made a few weeks/months ago (but i didn't think to save the source code...). It was not yet widely deployed, it was still in A/B test. Maybe they are deploying it now but not yet for us. 

So I won't be able to parse it and fix serposcope until I got the source code of this serp. I'll check in a few days.

**Comment by ron51** [comment]
@noguespi @jinjie Can the parser request the SERP again like a couple of times for that search term until it gets a proper BLOB object?  For now this should fix the issue and later you can add once we get the source code. I will try if I can get hold of the source code.

**Comment by noguespi** [comment]
It is not that simple because a SERP could be really empty and we don't want to retry in this case. I should have add a debug option in serposcope so it saves the original html source somewhere, useful for debugging.

**Comment by ron51** [comment]
Yes, did'nt realise the empty case. The debug option is a good idea and will help in future. How long do you think this will take to fix?

**Comment by ron51** [comment]
@noguespi the occurrence of empty BLOBs are increasing making it extremely difficult to track keywords. Can we have an admin setting for rechecking incase of empty BLOB, as mostly keywords never give empty SERPs.  The setting will be configurable from Admin.  

@jinjie are you too facing the same thing?

**Comment by jinjie** [comment]
@ron51 I too have empty BLOGS for affected keywords.

Will it be better to recheck specific keywords with checkboxes?

The setup now is only to recheck failed keywords. Since these keywords is not detected as failed, we cannot manually recheck these keywords.

**Comment by noguespi** [comment]
I managed to get a hand on those empty serps and it is exactly what I expected. It is the new SERP which display the favicon. Now I have the source code I will be able to fix it very soon.

**Comment by ron51** [comment]
Wow @noguespi  Thanks for the info

**Comment by noguespi** [comment]
Tell me if this build works https://serposcope.serphacker.com/download/2.11.0/ 

I have not tested them (tell me on which OS you used it).

**Comment by jinjie** [comment]
Deployed this build. Need some time to monitor the results and will update here.

Thanks @noguespi

**Comment by schnapps99** [comment]
Seems to solve the problem. 
But: 500 Keywords using proxies for scan:

old scan was around 1h and 80 captchas, 
New scan took 3,5h and 1200 (!!!) captchas.

**Comment by jinjie** [comment]
No noticeable difference for me. Numbers looks consistent since the last update to 2.11.0. Although mine is just 79 keywords.

**Comment by ron51** [comment]
@jinjie I didn't get time to test it yet. Did the main issue resolve with the latest build?

**Comment by jinjie** [comment]
> @jinjie I didn't get time to test it yet. Did the main issue resolve with the latest build?

Seem okay for the last 3 days run. Since the favicon appears periodically, i think need more time to really determine if it's fixed in the latest build.

**Comment by ron51** [comment]
@noguespi Just tested it thoroughly, the issue is resolved. Thanks mate for the quick turnaround.
