### ISSUE TITLE
IPV6 proxies support integration guide

### ISSUE THREAD

**Issue by puneetas3** [serphacker/serposcope#218]
Hi, I understand that serposcope don't support IPv6 proxies out of the box. I am looking to make changes to code and adapt for IPv6 proxies and compile. I need some pointers in this regard.

I got IPv6 proxies in this form 250.50.50.50:3128 (IPv4, that connects over IPv6). First thing I understand is that I need to setup my own IPv6 proxy judge. The proxy judge in this file supports only IPv4- 

> https://github.com/serphacker/serposcope/blob/ba4720bb676da03f85cca1c119fbf2a4a48fb23b/core/src/main/java/com/serphacker/serposcope/task/proxy/ProxyChecker.java

This proxy judge fails over IPv6. Can you help me understand what other part of the code needs modifications. I will try to get things sorted if I get pointers.

**Comment by chandlerbing26** [comment]
the form you have the proxies in I myself also have them.
Just add them to your proxies list from the admin menu, when you test them with serposcope it will show as error but try checking rank it will work and the searches will go through the proxies. I am using like this for a long time now.

**Comment by puneetas3** [comment]
@chandlerbing26 ok great, thanks mate.
