### ISSUE TITLE
Captcha Fails

### ISSUE THREAD

**Issue by jinjie** [serphacker/serposcope#228]
Are there any changes in Google's captcha recently? Both anti-captcha and 2captcha failed almost 100%. That shouldn't be the case.

Any one can shed some light on this?

**Comment by HostiberiGit** [comment]
I too, same error :(

**Comment by jinjie** [comment]
I am trying to make sense is it Google changed it's captcha or is it a Serposcope bug.

I have sent a support ticket to 2captcha. Hopefully it's nothing related to serposcope.

I can confirm that anti-captcha and 2captcha fails on my setup.

**Comment by noguespi** [comment]
hello, it is very likely to be a bug in serposcope and not the captcha service. I'm very busy I do my maximum to fix it this week.

**Comment by HostiberiGit** [comment]
Ohhh thanks noguespi, thank you very much friend

**Comment by ron51** [comment]
Thank you @noguespi as always. Just wondering why we did'nt encounter it before? 
@jinjie thanks for pointing it out. I was struggling to fetch the rankings since a couple of days and wondering what was the issue.

**Comment by ron51** [comment]
@jinjie did you also test with deathbycaptcha service?

**Comment by jinjie** [comment]
I did not use deathbycaptcha service. I only use anti-captcha and 2captcha.

I was looking through the codes the past few days but not sure where to
start the troubleshooting process. 😕

**Comment by ron51** [comment]
I think the recent Core update changed a few things in it's DOM because of which the captcha related code is failing. Do you know JAVA @jinjie ?

@noguespi  any update on when can this be fixed?

**Comment by jinjie** [comment]
I got this response from 2captcha:

> Hi!

> Google does not accept recaptcha tokens for google search. We making an investigation that will allow to override this limitation.

Does that mean it's a Google recent breaking change? 

@noguespi is it still a bug you still need to fix there? 

I can't find any other information of this Google recaptcha change.

**Comment by ron51** [comment]
Even I can't find any information about the captcha change. I hope this gets resolved soon.

**Comment by ron51** [comment]
I tried with deathbycaptcha service too, even that is failing @noguespi @jinjie

**Comment by ron51** [comment]
Did anyone figure out the issue? 
Also I think it will be nice to integrate it with multiple other captcha & proxy services. 

Like connect to a public proxy source, it can be really helpful.

@noguespi any update bro?

**Comment by jinjie** [comment]
@ron51 Chill... This project is supposed to be dead. It's nice of @noguespi to offer to look into it.

**Comment by ron51** [comment]
@jinjie true

**Comment by noguespi** [comment]
I did work a bit on it today. Google captcha solving changed and captcha service need to upgrade their API.

As far as I know, only anti-captcha updated its API at the moment. 

I tested it locally and it works, I will publish a patch for serposcope this week end.

- Imagetyperz is working on a fix.
- 2captchas I don't know, please @jinjie keep me informed when they update their API.
- deathbycaptcha asked them but no response so far

**Comment by jinjie** [comment]
There was a banner on 2captcha past two days informing about the failure but I do not see it now.

Just did a test again but returned with a different error.

```
[2020-05-29 00:20:32,607] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2020-05-29 00:20:32,607] [google-0] INFO  c.s.s.s.c.s.RandomCaptchaSolver - trying 2captcha
[2020-05-29 00:20:33,082] [google-0] INFO  c.s.s.s.c.s.RandomCaptchaSolver - 2captcha failed with NETWORK_ERROR
[2020-05-29 00:20:33,082] [google-0] INFO  c.s.s.s.c.s.RandomCaptchaSolver - all captcha solver failed
[2020-05-29 00:20:33,082] [google-0] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha error = NETWORK_ERROR
```

**Comment by jinjie** [comment]
@noguespi I guess they have updated their API:

https://2captcha.com/blog/google-search-recaptcha

**Comment by noguespi** [comment]
> @noguespi I guess they have updated their API:
> 
> https://2captcha.com/blog/google-search-recaptcha

yes it just happened

**Comment by noguespi** [comment]
Please try this build and tell me if it works : https://serposcope.serphacker.com/download/LATEST/

Only anticaptcha and 2captcha API is fixed. 

It may not works with deathbycaptcha  and imagetyperz because they didn't update their API yet.

**Comment by HostiberiGit** [comment]
OK, very thanks noguespi.

I am going to test in debian 9 and comment if it went well :)

**Comment by jinjie** [comment]
@noguespi I seem working for anti-captcha.

2captcha seem to be hit or miss. I will monitor this for a while and report if my next runs are successful.

**Comment by theblackfort** [comment]
@noguespi Thanks again for this update. Really appreciate your effort to help us out after you declared this as a dead project.

I owe you a beer/coffee for your contribution to the community :)

**Comment by highpec** [comment]
@noguespi 2Captcha still seems to not be working for me...

[2020-05-30 05:49:29,991] [google-2] INFO  c.s.s.s.c.s.RandomCaptchaSolver - 2captcha failed with NETWORK_ERROR
[2020-05-30 05:49:29,992] [google-2] INFO  c.s.s.s.c.s.RandomCaptchaSolver - all captcha solver failed
[2020-05-30 05:49:29,992] [google-2] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha error = NETWORK_ERROR

I manually extracted the update .jar file and replaced the files in the changelog into the old .jar file, instead of re-installing. I made 100% sure to replace every file in the changelog. This was done while the service was stopped, then I started it afterwards.

**Comment by highpec** [comment]
@jinjie Did 2Captcha end up working for you? I’m trying to avoid doing a full re-install if it’s not necessary. I manually extracted/updated the old .jar with new files from the change log.

For me, 2Captcha is failing 100% of the time with “NETWORK_ERROR”. Haven’t tested the other one yet.

**Comment by jinjie** [comment]
Just checked my logs. Indeed there is NETWORK_ERROR happening for 2captcha.

I use 2 captcha solver. Namely anti-captcha and 2captcha. 

Based on my logs, I don't think 2captcha is failing 100% for me. At least it doesn't look like it.

@noguespi from the codes, I see that 2captcha is invoking the api through http instead of https. Is it because of that?

I can understand the codes and compile them. But I am unsure how to do debugging on my dev. If someone can advise me how to use mvn, maybe I can try to fix it.

**Comment by highpec** [comment]
@noguespi @jinjie I can confirm that **anticaptcha works** 100% of the time, and **2Captcha fails** 100% of the time, at least for me. Hopefully there will be another update fixing the 2Captcha issue, until then, I'll just only use anticaptcha.

**Comment by loloseo** [comment]
Hello
Any news of Deathbycaptcha ?

**Comment by 2captcha** [comment]
> Just checked my logs. Indeed there is NETWORK_ERROR happening for 2captcha.
Sorry, that was an issue with SSL certificate on our side that caused the NETWORK_ERROR.

We've updated our api and added support for `data-s` `cookies` and `userAgent` parameters that you can pass to our API and we'll pass the data to our worker to use them during captcha solving. Also you can pass your proxy.

**Comment by ron51** [comment]
Thanks for the response @2captcha

**Comment by ron51** [comment]
I always used deathbycaptcha, time to move to @2captcha now

**Comment by ron51** [comment]
Has anticaptcha started failing again? It worked until yesterday. I am still getting NETWORK ERROR issue on anticaptcha

**Comment by manuhook** [comment]
Same here =(

`[2020-06-05 14:20:11,533] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT[refetch] status=[302] exception=[none]
[2020-06-05 14:20:11,534] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:http://xxxx/
[2020-06-05 14:20:11,625] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - trying with captcha recaptcha
[2020-06-05 14:20:11,626] [google-0] INFO  c.s.s.s.c.s.RandomCaptchaSolver - trying anticaptcha
[2020-06-05 14:20:38,710] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - got captcha response 03AGdBq27nu667vaqSolIFzLkEQzkndAl0Z0PwCy6H6NqyU13xc2W6zWbSnlNovJwLhftNC32W6tWl0BRvcGdfUjgNvmCC7Won9EdXoUSCF3Sum8m6dBzQWx5BkLD5b3pr49jXtEHC4XdoG87PBqZcarxGP7-X5eTN0Zo6urgSoSUitjVdh8-iySaYj0mxlF6mUseU2x3_uBB3pbRv9Rb416EiyDk1VdaojRbRH7jupntVT9EXqy4dN-KOB_S1u-haXUhtyxqeQAltGaEKalOutnTUo3F9k5p_Zt9Aeg7RkkT08jgRGW3Kl324YlQCqdfZdxIG4l23w_nlkfymOlKX7gWDX6e6-aMscsl5d-0AbOuQs43dyOBwDFQW13uIOD9sIbsh997GkGtTlWpB8gCXvlzkxUPeEDzICJSDT4pQPlxqyj1xJ8uTge-kbAJtarHMZ8OC73SD-Mze in 27 seconds from anticaptcha
[2020-06-05 14:20:40,024] [google-0] TRACE c.s.s.s.g.s.GoogleScraper - sleeping 58607 milliseconds
[2020-06-05 14:20:52,185] [google-1] INFO  c.s.s.s.c.s.RandomCaptchaSolver - anticaptcha failed with NETWORK_ERROR
[2020-06-05 14:20:52,185] [google-1] INFO  c.s.s.s.c.s.RandomCaptchaSolver - all captcha solver failed
[2020-06-05 14:20:52,185] [google-1] ERROR c.s.s.s.g.s.GoogleScraper - solver can't resolve captcha error = NETWORK_ERROR
`

**Comment by jinjie** [comment]
Closing this as this issue have been resolved with the latest patch for me.
