### ISSUE TITLE
Error mobile keywords

### ISSUE THREAD

**Issue by joska1993** [serphacker/serposcope#244]
My mobile keywords are not working. I don't see any error, it just doesn't extract the information from the serps.

**Info:**
Using mysql
It started to fail on the 28th. It used to work fine

![image](https://user-images.githubusercontent.com/4182345/139527427-6132b1e5-22c2-4012-885c-4568c3e09250.png)
![image](https://user-images.githubusercontent.com/4182345/139527528-b4d7d082-7029-44f7-a1a1-0b9ed3f6b018.png)

Thanks,

**Comment by pedropmv** [comment]
Same here, fails on 26th

**Comment by joska1993** [comment]
I think that the error comes from this "if"
https://github.com/serphacker/serposcope/blob/7f06788c86a8d9d63749afaab2704b254a6de1b9/scraper/src/main/java/com/serphacker/serposcope/scraper/google/scraper/GoogleScraper.java#L346

Maybe here:
https://github.com/serphacker/serposcope/blob/7f06788c86a8d9d63749afaab2704b254a6de1b9/scraper/src/main/java/com/serphacker/serposcope/scraper/google/scraper/GoogleScraper.java#L348

Perhaps the type of useragent used for mobile searches no longer displays the information in the same way.

`Mozilla/5.0 (Android 7.0; Mobile; rv:59.0) Gecko/59.0 Firefox/59.0`

Anyone who can contribute more?

**Comment by noguespi** [comment]
I'm going to fix it

**Comment by noguespi** [comment]
fixed, please download latest version (2.14.0) on https://serposcope.serphacker.com/
