### ISSUE TITLE
can't find captcha img tag

### ISSUE THREAD

**Issue by joska1993** [serphacker/serposcope#250]
Previously this message did not appear so much...

**Error in log:** can't find captcha img tag

[2022-01-13 22:51:00,607] [google-19] DEBUG c.s.s.s.g.s.GoogleScraper - noscript form detected, trying with captcha image
[2022-01-13 22:51:00,607] [google-19] DEBUG c.s.s.s.g.s.GoogleScraper - can't find captcha img tag

What can cause it?

**Comment by krzysztof-raciniewski** [comment]
I have noticed the same behavior for 2 days:

![image](https://user-images.githubusercontent.com/7010367/149493278-ee10c6d5-afa0-44c7-a46c-75665ecf67eb.png)

**Comment by noguespi** [comment]
I will check it out tomorrow

**Comment by mindfighter73** [comment]
I do have the same problem. I thought it was my captcha service and I changed it but the problem still remains.

**Comment by noguespi** [comment]
fixed in 2.15.0

**Comment by mindfighter73** [comment]
> fixed in 2.15.0

Super, thank you very much for all of your efforts.

**Comment by joska1993** [comment]
> fixed in 2.15.0

Thank you very much! ;)
