### ISSUE TITLE
Highcharts Dynamic Height

### ISSUE THREAD

**Issue by liveincan** [serphacker/serposcope#28]
Adding more keywords causes HighChart information to be squeezed. Does not re-size height. Requires dynamic height setup. See http://prntscr.com/77ma4u

**Comment by serphacker** [comment]
Screenshot was removed, I consider that people using a lot of keywords should use table view and not charts.

But anyway you are right, the graph should be resizable. I don't have quickfix for that, the whole rendering will be changed in v2 with responsive design and bigger layout.

**Comment by liveincan** [comment]
Screenshot was removed - had personal info. Original Chart Image link: http://prntscr.com/77ma4u

Changed line 20 in highcharts.php from:
echo '<div id="'.$idDiveu.'" style="height: '.$height.'px; margin: 0 auto"></div>';
to:
echo '<div id="'.$idDiveu.'" style="height:100%; position:absolute; margin: 0 auto"></div>';

Corrected chart layout: http://prntscr.com/77u3l9

**Comment by liveincan** [comment]
Changed line 20 in highcharts.php from:
`'<div id="'.$idDiveu.'" style="height: '.$height.'px; margin: 0 auto"></div>';`
to:
` '<div id="'.$idDiveu.'" style="height:100%; position:absolute; margin: 0 auto"></div>';`
