### ISSUE TITLE
Fail to Run

### ISSUE THREAD

**Issue by geopayme** [serphacker/serposcope#30]
I get this error when I click RUN ALL... any thoughts?

Fatal error: Call to undefined function posix_getsid() in /home/content/05/12974005/html/hmDev/_sE_rp/inc/functions.php on line 150

**Comment by serphacker** [comment]
because your hosting provider doesn't allow this function, it's not a default php setup, your shared hosting is too restrictive, use another hoster or use a VPS.

**Comment by geopayme** [comment]
Thanks for the heads up.
