### ISSUE TITLE
Ranking not displayed

### ISSUE THREAD

**Issue by shellysaju** [serphacker/serposcope#32]
I have installed it after reading the documentation. But I am not getting
the rank, there is no issues on the log, also i have looked at cron.php and i understand that no values are getting to insert rank into database

**Comment by serphacker** [comment]
did you search the forum for similar problem ? I have already heard about a
similar issue, can't help you without explicit error message

Le mar. 28 juil. 2015 à 17:16, shellysaju <notifications@github.com> a
écrit :

> I have installed it after reading the documentation. But I am not getting
> the rank, there is no issues on the log, also i have looked at cron.php
> and i understand that no values are getting to insert rank into database
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serphacker/serposcope/issues/32>.
>
-- 
Pierre Noguès
sécurité - dev - adminsys
http://nogues.pro/
