### ISSUE TITLE
Niche/Keyword SERP Movemend Monitor Feature

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#33]
Is it possible to have/add an option to monitor serp movement for specific keyword over time? 
For example, to see what are top 10 and top 20 pages that rank for a specific keyword in google desired country, over time.
This is mainly used to see how updates on google affects rankings on keywords, even a niche. Here is a an example of what I mean http://i.imgur.com/L00SBVm.png

So instead of having monitor keyword for domain like we have now see here http://serposcope.serphacker.com/en/screenshots/highcharts.png to add an option to monitor serp movement per keyword based. How pages move in and out from top 10 or top 20 .

I think that Serpscope has most feature, not sure how hard is to implement my request, but @serphacker I'm happy to pay for this addon if you can build it. Please let me know if you can and PM me the price you want for adding this feature.

Thanks
Sorasma

**Comment by serphacker** [comment]
Hi, I really want to implement this feature but I don't have the time now. Also, I can't add this feature in the current version of serposcope, it need to be totaly rebuild from scratch.

The only way I could do serposcope 2 quickly is by doing a crowdfunding. I'm thinking about it but serposcope is used by a limited number of people and I don't think I could raise enough money.

**Comment by Sorasma** [comment]
Can you estimate a cost for this. Maybe I can find people who want to join this. Please let me know. If you need in private, please give me a way to contact you privately

**Comment by serphacker** [comment]
Please contact me at noguespi@gmail.com

**Comment by serphacker** [comment]
duplicate #12
