### ISSUE TITLE
search volume for keywords

### ISSUE THREAD

**Issue by serphacker** [serphacker/serposcope#53]
Is it only retrievable via adwords API ?
Is adwords API free ?

to test

**Comment by LeFrenchie** [comment]
Je crains que la seule solution soit de scraper un compte ADWORDS.

**Comment by serphacker** [comment]
Won't support adwords API (because API access is hard to obtain and adwords team won't release an api key just for keyword volume);
However, will add search_volume and cpc field to keyword, and ability to import adwords dump.

**Comment by serphacker** [comment]
see #106
