### ISSUE TITLE
Inconsistent summary after run deletion

### ISSUE THREAD

**Issue by slicksps** [serphacker/serposcope#60]
I've been running daily, everything has been smooth, I have deleted errored tasks. However today's results are showing that all keywords have only just been added despite previous data. Happy to run reports, extracts etc for devs.

Screenshots attached

![in problem](https://cloud.githubusercontent.com/assets/2051705/12291659/6da2f73a-b9e0-11e5-99ee-241c62c4fc66.JPG)
![wins and losses](https://cloud.githubusercontent.com/assets/2051705/12291657/6d9fd546-b9e0-11e5-988b-c852eadeddf3.JPG)
![tasks](https://cloud.githubusercontent.com/assets/2051705/12291658/6da05cc8-b9e0-11e5-8b4c-e8b0a9295fbb.JPG)

**Comment by serphacker** [comment]
It is because of deleted failed run. Serposcope doesn't rescan all the SERP each time a run is deleted.

To fix that, you can trigger a full rescan of all the run and all the SERP by deleting your website, and adding it again to your group.
