### ISSUE TITLE
Getting On Same Date 2 SERP Checks

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#64]
Not sure why, but I'm getting on same date 2 serp checks in the chart.
Here is prt sc: https://app.box.com/s/up3ktw4kwnvh7hai059pf95xlrcmu85j

Is it because I have cron time setup by "00:30" ? (se prt sc here https://app.box.com/s/0zixfczjj8gwg86oijzs1xipok4vce9x )

**Comment by serphacker** [comment]
It's a minor issue in the javascript library, don't worry there is no 2 checks done. There is only checks where there are "dots" on the chart. The dates are just not at the right place. I'll fix it.

**Comment by serphacker** [comment]
minor issue, wontfix, the chart library is going to change in v3 anyway
