### ISSUE TITLE
Enhance keyword chart view (fix huge legend and provide select top XXX urls)

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#66]
1. Here is how "Split View " shows when I select first 20 url's in top 10: https://db.tt/t3Yk6kVh
Maybe you can offer option to only show Chart + Serp pannels like this https://db.tt/1p3FnRhc and remove the other part with url's only, doesn't make sense to have them
Apply same option for "Split View" and "Chart View"

Idea is that nobody wants to see the part with lots of urls like here https://db.tt/hPiQkDS4 . 
Just select 20-30 url's and look how annoying it looks, better add only "Chart" + "Serp Table"

2. Please, please , please add option to select nr of "btn-draw-chart active" from class="btn-draw-chart active" to see instead of clicking on each url. maybe a option like this one : 
"Select first ..... url's" to see in chart
Example:
"Select first 5 url's"
"Select first 10 url's"
"Select first 15 url's"
.....etc..

This will help alot. Just think about when you want to see first 30 url's in serp, you need to click on 30 class="btn-draw-chart" just to activate them

**Comment by serphacker** [comment]
I agree.

**Comment by Alexvander** [comment]
Any to do date estimation on this feature?
