### ISSUE TITLE
Advanced search feature in "Groups" and each separate Group

### ISSUE THREAD

**Issue by Sorasma** [serphacker/serposcope#68]
When you start to add lots of groups and in each group you have lots of keywords it's starts to be a bit harder to find what you want. 
My suggestions are:
1. When creating a Group beside the "Name" also offer option to add "Tags" , by adding multiple tags it's easier to filter search, here is example: https://db.tt/8BL00H5l and a Serach function in each column like here https://db.tt/aDycVQ9Y
Also, a simple search function in each group, for "Websites" and "Searches" will also solve problems with searching.

Another solution is to also add advanced operators inside the search. You also take into consideration advanced search operators using logic expressions, mainly “AND”, “OR” and “NOT” expressions.
Example: 
a. Search in Name: weight AND (lose OR best) AND water NOT amazon
b. Search in Tags: word1 OR word2 OR word3 NOT word4 = Here we get all results that include word1. or word 2 or word 3 but doesn't include word4, even if they include for example word1 but if they include word1+word4 this will not be shown

**Comment by serphacker** [comment]
> Also, a simple search function in each group, for "Websites" and "Searches" will also solve problems with searching.

It is already doable with the left sidebar.

The keyword management/search will be improved in future release, but not sure i'll integrate tags. wontfix for now.
