### ISSUE TITLE
Suggestions, coquilles..

### ISSUE THREAD

**Issue by LeFrenchie** [serphacker/serposcope#69]
Hello,

Coquille d'orthographe : dans Configuration Google, il manque l'apostrophe dans le d d'erreur > Nombre de tentatives en cas derreur réseau

Pour les suggestions :

- J'imagine que la possibilité de checker simplement un groupe a déjà été remonté ? (hyper utile et utilisé).
- La possibilité de sélectionner les proxys qui sont en "ERROR" pour soit un recheck sur eux, soit leurs suppression via un bouton afin d'éviter d'avoir 80 checkbox à cocher à la main ;-)
- Coté cron, la possibilité dans les options globales de spécifier la planification comme un cron classique (et non tous les jours comme actuellement), mais j'irai encore plus loin, la possibilité de spécifier pour chaque groupe un refresh différent permettant de checker plus ou moins régulièrement selon l'importance des groupes et gagner du temps sur l'analyse. 
- Pouvoir faire des groupes de groupes ? Genre : Sites clients > Client A, Client B, ...
- Pouvoir faire des exports : CSV, PDF ?
- La possibilité d'avoir le calcul des possibilités au fur et à mesure du scrap (pour les groupes finis) et ne pas attendre la main de liste des MCs ?
- J'ai également observé qu'au lancement d'un check de positions, dans l'affichage des taches, je vois que les 10 premières secondes, il me bouffe 20/30 captchas puis plus rien ou de manière épisodique, pourquoi ? un bug ?

Merci pour ton outil fabuleux.

**Comment by serphacker** [comment]
Ok je prends note.

Pour les 20/30 captchas au début uniquement c'est normal si tu utilises des proxies, ça veut meme dire que ça fonctionne très bien. En gros chaque proxy doit casser son captcha (s'il est marqué par Google comme abusif), après Google dépose un cookie comme quoi cette IP a validé le captcha. Ce cookie n'est valide que pour  une ip (donc un proxy) et un certain nombre de requête, c'est pourquoi il n'y a pas plus besoin de casser un captcha pendant un certain temps.

**Comment by serphacker** [comment]
not a specific issue, too broad
