### ISSUE TITLE
Temps anormalement long dans le calcul des positions.

### ISSUE THREAD

**Issue by LeFrenchie** [serphacker/serposcope#70]
J'ai environ 2000 MCs (10K à terme) avec 50 proxies privés et un service de captcha activé.

Je suis entrain de faire des tests du format le plus rentable (temps/coût) pour un nombre donné de MCs.
Dans ce sens, je teste avec les paramètres suivants : 

Timeout : 1sec
Threads : 1
1 page avec 100 res.

Mathématiquement, nous avons 2000 MC x 1 sec soit au mieux 2000 sec soit 33 min env.
Si le proxy ou le temps de récupérer la SERP prend 1sec de plus, nous pouvons monter à disons 1H de calcul ?
Sauf que dans mon cas : j'ai ma tache qui a commencé à 10h00 et j'en suis à 40% après 1h20, et l'estimation me donne encore 1h20. pourquoi ?
J'ai d'ailleurs remarqué à chaque fois une progression très rapide sur les premières minutes puis un ralentissement violent ensuite (sans pour autant être banni et/ou déclenché des captchas).
Quand on regarde le log, on voit au début qu'il suit bien la cadence, mais plus à un certain moment.

Merci pour ton retour.

ps : as tu des retours d'xp pour le bon format sur du gros volume ?

**Comment by LeFrenchie** [comment]
Il semblerai après analyse que 50% de mes proxies "tombent" coté réseau (buyproxies), et ca serai cela qui plombent les temps de scrap.

**Comment by serphacker** [comment]
il faut également prendre en compte le temps pour casser les captchas qui
peut parfois être long, les réessais etc. Aussi le run peut etre plus long
car les proxies peuvent commencer à être blacklistés ou rencontrer plus de
captchas. Ça dépend de plein de facteurs. Le temps restant est une
estimation qui n'est pas fiable à 100% (tous les proxies ne vont pas à la
même vitesse, tous n'ont pas des captchas etc.).

Je pense qu'en regardant les logs complet tu dois pouvoir comprendre
pourquoi ça ralentit au bout d'un certain temps.

Il faut utiliser mysql à partir de 1000 keywords, non pas encore de retours
pour du gros volume.


Le ven. 22 janv. 2016 à 11:22, LeFrenchie <notifications@github.com> a
écrit :

> J'ai environ 2000 MCs (10K à terme) avec 50 proxies privés et un service
> de captcha activé
>
> Je suis entrain de faire des tests du format le plus rentable (temps/coût)
> pour un nombre donné de MCs
> Dans ce sens, je teste avec les paramètres suivants :
>
> Timeout : 1sec
> Threads : 1
> 1 page avec 100 res
>
> Mathématiquement, nous avons 2000 MC x 1 sec soit au mieux 2000 sec soit
> 33 min env
> Si le proxy ou le temps de récupérer la SERP prend 1sec de plus, nous
> pouvons monter à disons 1H de calcul ?
> Sauf que dans mon cas : j'ai ma tache qui a commencé à 10h00 et j'en suis
> à 40% après 1h20, et l'estimation me donne encore 1h20 pourquoi ?
> J'ai d'ailleurs remarqué à chaque fois une progression très rapide sur les
> premières minutes puis un ralentissement violent ensuite (sans pour autant
> être banni et/ou déclenché des captchas)
> Quand on regarde le log, on voit au début qu'il suit bien la cadence, mais
> plus à un certain moment
>
> Merci pour ton retour
>
> ps : as tu des retours d'xp pour le bon format sur du gros volume ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serphacker/serposcope/issues/70>.
>
-- 
Pierre Noguès
sécurité - dev - adminsys
http://nogues.pro/
