### ISSUE TITLE
Error SQL, pourquoi ?

### ISSUE THREAD

**Issue by LeFrenchie** [serphacker/serposcope#82]
Hello @serphacker ,

J'ai eu de l'echec sur des taches avec ce genre d'erreur SQL (nous sommes sur base MySQL avec env 8000KW)
 Une idée de la source du pb ? Merci !

**Comment by serphacker** [comment]
Format le message ou utilise gist.github.com car je n'arrive pas à lire

**Comment by LeFrenchie** [comment]
J'ai mis en GIST j'espère que c'est plus visible de ton coté : 
https://gist.github.com/LeFrenchie/2c686b4743c8f420c916

**Comment by serphacker** [comment]
Intéressant, as tu fait des modifications sur la base de données manuellement (ligne de commande, phpmyadmin) ?

**Comment by LeFrenchie** [comment]
Non juste le fait d'être en base mysql et non celle intégrée.
Peut être qu'il y a une corrélation avec un temps de pause plus réduit et un gros nombre de mc ?

**Comment by serphacker** [comment]
Non ça ne peut pas expliquer ce bug, est ce qu'il se produit à chaque run ? Aussi, si tu es sous Linux peux tu me faire voir le contenu de /var/log/serposcope/startup.log ?

**Comment by serphacker** [comment]
Et aussi, quelle version de serposcope ?

**Comment by LeFrenchie** [comment]
C'est au boulot donc je ne peux pas te dire encore le contenu du log,
concernant la version c'est avant dernière, celle de janvier.
Et non ca ne le fait pas à chaque fois, ca le fait quand le cron prend
bcp trop de temps (14h00 au lieu de 2h00 habituellement).

2016-02-14 18:53 UTC+01:00, SERP Hacker <notifications@github.com>:

**Comment by serphacker** [comment]
Oui c'est une conséquence du bug, car le bug fait crasher les threads un par un (donc c'est de plus en plus lent), et à la fin le dernier thread crash ce qui provoque un échec de la tâche.

Il me faudra également le log complet de la tâche qui a foiré et pas juste un extrait (dans /admin/logs tu as une fonction log anonyme). Tu peux mail à support@serphacker.com si tu préfères.

**Comment by LeFrenchie** [comment]
Email envoyé :)

**Comment by serphacker** [comment]
fixed by 416514ebf31532f3c2cde83cd982e508a1d7e8f6
