### ISSUE TITLE
Dynamic proxy list

### ISSUE THREAD

**Issue by dsampaolo** [serphacker/serposcope#85]
I have a list of proxy, changing monthly.
I'd like to be able to reference my proxy list in the form : https://user:pass@mysite.tld/proxies.txt
and have it checked every day, or a button "download & replace proxies"

**Comment by LeFrenchie** [comment]
+1 Steph.

**Comment by serphacker** [comment]
This feature was in v1. Can be done quickly because proxy checking is already implemented.

**Comment by ericfaucon** [comment]
yes !

**Comment by Andrii-D** [comment]
+1

**Comment by serphacker** [comment]
duplicate #55
