### ISSUE TITLE
user-agent change

### ISSUE THREAD

**Issue by ericfaucon** [serphacker/serposcope#86]
Hi, 
According to that article:
[(http://searchnewscentral.com/20110928186/General-SEO/how-to-scrape-search-engines-without-pissing-them-off.html)]
 it seems that a scraper is less likely to be blocked if it uses a different user-agent.
For slow/small scraping, I think it would be a good idea to implement that;
having an updatable list of different user-agent and query Google with random UA.

What do you think ?

**Comment by serphacker** [comment]
I think it's a common belief. Unless someone give me serious proof using differents user agents allow to scrap more without blocked, I won't implement this feature. There is so much more important thing to do now. But maybe later.
