### ISSUE TITLE
Check whether or not to use proxies

### ISSUE THREAD

**Issue by ericfaucon** [serphacker/serposcope#87]
I'd like sometimes to check a few KW for a specific group.
I know there's a thread for that, but in parallel, I'd like to check whether or not to use proxies.

For now, if there are proxies, they're used. My list is quite big, and for small checks, I'd rather not use them. 

Could we have a checkbox in config to enable/disable the use of proxies ?

**Comment by serphacker** [comment]
We will see that when the "quick check feature" allowing to check a few (or all) keywords from any group will be implemented. But I don't think I will implement it.
Why not use proxy ?

**Comment by ericfaucon** [comment]
My boss doesn't want to spend a dime on a proxy, and public proxies are often CAPTCHAed by Google...
