### ISSUE TITLE
Search Volume

### ISSUE THREAD

**Issue by Roman-121** [serphacker/serposcope#95]
Hello

I think this would be very good app if you add two things:
1. option for search volume of every keyword (even just field where we can manual add search volume would be ok, if auto is to hard to do)
1. Improve your scoring math. Now every 1 place get same points but it is very big difference if keyword with 10.000 searches in on first place or it is there keyword with few searches in whole month.

If there would be option for search volume you can use math to set value calculated from google rank and search volume... Then points would be more accurate and usefull

BR Roman

**Comment by serphacker** [comment]
duplicate #106
